In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.api as sm
from numpy.polynomial.polynomial import polyfit
from sklearn.linear_model import LogisticRegression
import seaborn as sns
import statsmodels.stats.tests.test_influence
from sklearn.feature_selection import RFE
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
from sklearn.model_selection import train_test_split, cross_val_score

# Problem definition

To build a model to predict if the shipments are will reach on time or not.

In [8]:
df=pd.read_csv("shipments.csv")

In [9]:
df.head(5)

ID Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0   1               D           Flight                    4                2   
1   2               F           Flight                    4                5   
2   3               A           Flight                    2                2   
3   4               B           Flight                    3                3   
4   5               C           Flight                    2                2   

   Cost_of_the_Product  Prior_purchases Product_importance Gender  \
0                  177                3                low      F   
1                  216                2                low      M   
2                  183                4                low      M   
3                  176                4             medium      M   
4                  184                3             medium      F   

   Discount_offered  Weight_in_gms  Reached.on.Time_Y.N  
0                44           1233                    1  
1                59           3088                    1  
2                48           3374                    1  
3                10           1177                    1  
4                46           2484                    1

In [10]:
df.shape

(10999, 12)

In [5]:
df.describe()

ID  Customer_care_calls  Customer_rating  Cost_of_the_Product  \
count  10999.00000         10999.000000     10999.000000         10999.000000   
mean    5500.00000             4.054459         2.990545           210.196836   
std     3175.28214             1.141490         1.413603            48.063272   
min        1.00000             2.000000         1.000000            96.000000   
25%     2750.50000             3.000000         2.000000           169.000000   
50%     5500.00000             4.000000         3.000000           214.000000   
75%     8249.50000             5.000000         4.000000           251.000000   
max    10999.00000             7.000000         5.000000           310.000000   

       Prior_purchases  Discount_offered  Weight_in_gms  Reached.on.Time_Y.N  
count     10999.000000      10999.000000   10999.000000         10999.000000  
mean          3.567597         13.373216    3634.016729             0.596691  
std           1.522860         16.205527    1635.377251             0.490584  
min           2.000000          1.000000    1001.000000             0.000000  
25%           3.000000          4.000000    1839.500000             0.000000  
50%           3.000000          7.000000    4149.000000             1.000000  
75%           4.000000         10.000000    5050.000000             1.000000  
max          10.000000         65.000000    7846.000000             1.000000

In [13]:
df.set_index('ID',inplace=True)

In [14]:
df.head(5)

Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
ID                                                                          
1                D           Flight                    4                2   
2                F           Flight                    4                5   
3                A           Flight                    2                2   
4                B           Flight                    3                3   
5                C           Flight                    2                2   

    Cost_of_the_Product  Prior_purchases Product_importance Gender  \
ID                                                                   
1                   177                3                low      F   
2                   216                2                low      M   
3                   183                4                low      M   
4                   176                4             medium      M   
5                   184                3             medium      F   

    Discount_offered  Weight_in_gms  Reached.on.Time_Y.N  
ID                                                        
1                 44           1233                    1  
2                 59           3088                    1  
3                 48           3374                    1  
4                 10           1177                    1  
5                 46           2484                    1

# Null value & data type check

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10999 entries, 1 to 10999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Warehouse_block      10999 non-null  object
 1   Mode_of_Shipment     10999 non-null  object
 2   Customer_care_calls  10999 non-null  int64 
 3   Customer_rating      10999 non-null  int64 
 4   Cost_of_the_Product  10999 non-null  int64 
 5   Prior_purchases      10999 non-null  int64 
 6   Product_importance   10999 non-null  object
 7   Gender               10999 non-null  object
 8   Discount_offered     10999 non-null  int64 
 9   Weight_in_gms        10999 non-null  int64 
 10  Reached.on.Time_Y.N  10999 non-null  int64 
dtypes: int64(7), object(4)
memory usage: 1.0+ MB


In [16]:
df.isna().sum()

Warehouse_block        0
Mode_of_Shipment       0
Customer_care_calls    0
Customer_rating        0
Cost_of_the_Product    0
Prior_purchases        0
Product_importance     0
Gender                 0
Discount_offered       0
Weight_in_gms          0
Reached.on.Time_Y.N    0
dtype: int64

In [17]:
df.isnull()

Warehouse_block  Mode_of_Shipment  Customer_care_calls  \
ID                                                              
1                False             False                False   
2                False             False                False   
3                False             False                False   
4                False             False                False   
5                False             False                False   
...                ...               ...                  ...   
10995            False             False                False   
10996            False             False                False   
10997            False             False                False   
10998            False             False                False   
10999            False             False                False   

       Customer_rating  Cost_of_the_Product  Prior_purchases  \
ID                                                             
1                False                False            False   
2                False                False            False   
3                False                False            False   
4                False                False            False   
5                False                False            False   
...                ...                  ...              ...   
10995            False                False            False   
10996            False                False            False   
10997            False                False            False   
10998            False                False            False   
10999            False                False            False   

       Product_importance  Gender  Discount_offered  Weight_in_gms  \
ID                                                                   
1                   False   False             False          False   
2                   False   False             False          False   
3                   False   False             False          False   
4                   False   False             False          False   
5                   False   False             False          False   
...                   ...     ...               ...            ...   
10995               False   False             False          False   
10996               False   False             False          False   
10997               False   False             False          False   
10998               False   False             False          False   
10999               False   False             False          False   

       Reached.on.Time_Y.N  
ID                          
1                    False  
2                    False  
3                    False  
4                    False  
5                    False  
...                    ...  
10995                False  
10996                False  
10997                False  
10998                False  
10999                False  

[10999 rows x 11 columns]

In [18]:
df.isnull().values.any()

False

In [19]:
df.isna()

Warehouse_block  Mode_of_Shipment  Customer_care_calls  \
ID                                                              
1                False             False                False   
2                False             False                False   
3                False             False                False   
4                False             False                False   
5                False             False                False   
...                ...               ...                  ...   
10995            False             False                False   
10996            False             False                False   
10997            False             False                False   
10998            False             False                False   
10999            False             False                False   

       Customer_rating  Cost_of_the_Product  Prior_purchases  \
ID                                                             
1                False                False            False   
2                False                False            False   
3                False                False            False   
4                False                False            False   
5                False                False            False   
...                ...                  ...              ...   
10995            False                False            False   
10996            False                False            False   
10997            False                False            False   
10998            False                False            False   
10999            False                False            False   

       Product_importance  Gender  Discount_offered  Weight_in_gms  \
ID                                                                   
1                   False   False             False          False   
2                   False   False             False          False   
3                   False   False             False          False   
4                   False   False             False          False   
5                   False   False             False          False   
...                   ...     ...               ...            ...   
10995               False   False             False          False   
10996               False   False             False          False   
10997               False   False             False          False   
10998               False   False             False          False   
10999               False   False             False          False   

       Reached.on.Time_Y.N  
ID                          
1                    False  
2                    False  
3                    False  
4                    False  
5                    False  
...                    ...  
10995                False  
10996                False  
10997                False  
10998                False  
10999                False  

[10999 rows x 11 columns]

In [20]:
df.duplicated()

ID
1        False
2        False
3        False
4        False
5        False
         ...  
10995    False
10996    False
10997    False
10998    False
10999    False
Length: 10999, dtype: bool

There is no null value present in side the data and also the data types of all attributes are appropriate

# Label encoding

In [21]:
label_encoder = preprocessing.LabelEncoder()
df['Mode_of_Shipment']= label_encoder.fit_transform(df['Mode_of_Shipment'])
df['Mode_of_Shipment'].unique()

array([0, 2, 1])

In [22]:
label_encoder = preprocessing.LabelEncoder()
df['Product_importance']= label_encoder.fit_transform(df['Product_importance'])
df['Product_importance'].unique()

array([1, 2, 0])

In [23]:
label_encoder = preprocessing.LabelEncoder()
df['Warehouse_block']= label_encoder.fit_transform(df['Warehouse_block'])
df['Warehouse_block'].unique()

array([3, 4, 0, 1, 2])

In [24]:
label_encoder = preprocessing.LabelEncoder()
df['Gender']= label_encoder.fit_transform(df['Gender'])
df['Gender'].unique()

array([0, 1])

# XG BOOST

In [36]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

In [37]:
X=df.drop(['Warehouse_block','Mode_of_Shipment','Customer_care_calls','Customer_rating','Cost_of_the_Product','Prior_purchases','Product_importance','Gender','Discount_offered','Weight_in_gms'],axis=1)
y=df['Reached.on.Time_Y.N']

In [26]:
X=df.iloc[:,:-1]

In [27]:
X

Warehouse_block  Mode_of_Shipment  Customer_care_calls  \
ID                                                              
1                    3                 0                    4   
2                    4                 0                    4   
3                    0                 0                    2   
4                    1                 0                    3   
5                    2                 0                    2   
...                ...               ...                  ...   
10995                0                 2                    4   
10996                1                 2                    4   
10997                2                 2                    5   
10998                4                 2                    5   
10999                3                 2                    2   

       Customer_rating  Cost_of_the_Product  Prior_purchases  \
ID                                                             
1                    2                  177                3   
2                    5                  216                2   
3                    2                  183                4   
4                    3                  176                4   
5                    2                  184                3   
...                ...                  ...              ...   
10995                1                  252                5   
10996                1                  232                5   
10997                4                  242                5   
10998                2                  223                6   
10999                5                  155                5   

       Product_importance  Gender  Discount_offered  Weight_in_gms  
ID                                                                  
1                       1       0                44           1233  
2                       1       1                59           3088  
3                       1       1                48           3374  
4                       2       1                10           1177  
5                       2       0                46           2484  
...                   ...     ...               ...            ...  
10995                   2       0                 1           1538  
10996                   2       0                 6           1247  
10997                   1       0                 4           1155  
10998                   2       1                 2           1210  
10999                   1       0                 6           1639  

[10999 rows x 10 columns]

In [28]:
y=df.iloc[:,-1]

In [29]:
y

ID
1        1
2        1
3        1
4        1
5        1
        ..
10995    1
10996    0
10997    0
10998    0
10999    0
Name: Reached.on.Time_Y.N, Length: 10999, dtype: int64

In [32]:
train, test = train_test_split(df, test_size = 0.5, random_state = 0)

In [33]:
train[:5]

Warehouse_block  Mode_of_Shipment  Customer_care_calls  Customer_rating  \
ID                                                                              
5062                1                 1                    4                2   
978                 4                 2                    4                5   
9646                1                 2                    5                4   
8188                1                 2                    3                1   
9207                0                 2                    3                2   

      Cost_of_the_Product  Prior_purchases  Product_importance  Gender  \
ID                                                                       
5062                  222                3                   1       1   
978                   223                3                   2       0   
9646                  176                6                   2       1   
8188                  218                4                   1       1   
9207                  226                2                   1       1   

      Discount_offered  Weight_in_gms  Reached.on.Time_Y.N  
ID                                                          
5062                 4           5919                    0  
978                 63           2427                    1  
9646                 9           4605                    0  
8188                 6           5480                    1  
9207                10           4254                    0

In [34]:
train_X = train.iloc[:,:-1]
train_y = train.iloc[:,-1]
test_X = test.iloc[:,:-1]
test_y = test.iloc[:,-1]

In [38]:
model = XGBClassifier()

In [39]:
model.fit(train_X,train_y)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [40]:
predict_train=model.predict(train_X)
print(predict_train)

[0 1 0 ... 0 1 1]


In [41]:
accuracy_train=accuracy_score(train_y, predict_train)
print(accuracy_train)

0.9472631387525005


In [42]:
model.fit(test_X,test_y)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=0,
              reg_alpha=0, reg_lambda=1, ...)

In [43]:
predict_test=model.predict(test_X)
print(predict_test)

[0 0 1 ... 0 0 1]


In [44]:
accuracy_test=accuracy_score(test_y, predict_test)
print(accuracy_test)

0.9336363636363636


# Support vector machine